src/gallery/urls.py
#    This file is part of picdo.

#    picdo is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    picdo is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with picdo.  If not, see <https://www.gnu.org/licenses/>.

from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.contrib.auth.views import LoginView, LogoutView
from gallery import views

app_name = 'gallery'

urlpatterns = [
	# gallery
	url(r'^$', 
		RedirectView.as_view(url='album/'), 
		name='gallery'
	),
	# picture
	url(r'^picture/(?P<picture_id>[0-9]+)/$',
		views.PictureView.as_view(),
		name='picture'
	),
	# album
	url(r'^album/$', 
		views.AlbumView.as_view(), 
		name='album'
	),
	url(r'^album/(?P<album_id>[0-9]+)/$', 
		views.AlbumView.as_view(), 
		name='album'
	),
	url(r'^album/(?P<album_id>[0-9]+)/(?P<page_id>[0-9]+)/$', 
		views.AlbumView.as_view(), 
		name='album'
	),
	# library
	url(r'^library/$', 
		views.LibraryView.as_view(), 
		name='library'
	),
	# settings
	url(r'^settings/$', 
		views.SettingsView.as_view(), 
		name='settings'
	),
	# register
	url(r'^register/$', 
		views.RegisterView.as_view(), 
		name='register'
	),
	# login
	url(r'^login/$', 
		LoginView.as_view(extra_context={
			'title': 'Connecte-toi',
			'version': views.VERSION,
			'appName': views.TITLE
		}),
		name='login'
	),
	# logout
	url(r'^logout/$', 
		LogoutView.as_view(extra_context={
			'title': 'Déconnecté',
			'version': views.VERSION,
			'appName': views.TITLE
		}),
		name='logout'
	)
]

src/picdo/urls.py
#    This file is part of picdo.

#    picdo is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    picdo is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with picdo.  If not, see <https://www.gnu.org/licenses/>.

from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url, static

urlpatterns = [
	url(r'', include('gallery.urls', namespace='gallery')),
	url(r'^admin/', admin.site.urls)
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/gallery/forms.py
#    This file is part of picdo.

#    picdo is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    picdo is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with picdo.  If not, see <https://www.gnu.org/licenses/>.

from django import forms

from .models import Picture


class ErrorList(forms.utils.ErrorList):
	def __str__(self):
		return self.as_divs()

	def as_divs(self):
		if not self:
			return ''
		return '<div class="errorlist">{}</div>'.format( \
			''.join('<p>{}</p>'.format(e) for e in self)
		)


class PictureForm(forms.ModelForm):
	class Meta:
		model = Picture
		fields = ('image',)
		widgets = {
			'image': forms.ClearableFileInput(attrs={
				'onchange': 'document.getElementById("upload-form").submit();',
				'multiple': True
			})
		}

src/gallery/views.py
#    This file is part of picdo.

#    picdo is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    picdo is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with picdo.  If not, see <https://www.gnu.org/licenses/>.

import datetime
import math
import re
import os
import zipfile

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin

from django.conf import settings
from django.core.files.base import ContentFile
from django.db.models import CharField, QuerySet
from django.db.models.functions import Lower
from django.http import HttpResponseForbidden, FileResponse
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views.generic.base import View

from .forms import ErrorList, PictureForm
from .models import Picture, Album, UserSettings
from .utils import get_illegible_name, translate_month

CharField.register_lookup(Lower)

VERSION = '0.8.1'
TITLE = 'picdo'


def get_or_create_album(**filters):
	if Album.objects.filter(**filters).exists():
		album = Album.objects.get(**filters)
	else:
		album = Album(**filters)
		album.save()
	return album


def get_or_create_user_settings(user):
	if UserSettings.objects.filter(user=user).exists():
		user_settings = UserSettings.objects.get(user=user)
	else:
		album = get_or_create_album(user=user, category='S', name='gallery')
		user_settings = UserSettings(user=user, current_album=album)
		user_settings.save()
	return user_settings


def get_album_from_id(user, album_id=None):
	if album_id is None:
		user_settings = get_or_create_user_settings(user)
		album = user_settings.current_album
	else:
		album = get_object_or_404(Album, pk=album_id, user=user)
	return album


def get_picture_shape(picture):
	ratio = picture.width / picture.height

	if ratio < 0.86:
		return 'h'
	elif ratio > 1.14:
		return 'l'
	return 's'


class BaseView(View):
	title = TITLE
	version = VERSION
	template_name = 'gallery/base.html'
	view_name = 'gallery:gallery'
	nav_bar = True
	nav_selected = ()
	action_elements = ()
	action_search_view = view_name
	message = ''

	def get(self, request, *args, **kwargs):
		return render(request, self.template_name, self.get_base_context())

	def get_base_context(self):
		return {
			'title': self.title,
			'appName': TITLE,
			'version': self.version,
			'viewName': self.view_name,
			'navBar': self.nav_bar,
			'navSelected': self.nav_selected,
			'actionElements': self.action_elements,
			'actionSearchView': self.action_search_view,
			'message': self.message
		}


class LibraryView(LoginRequiredMixin, BaseView):
	title = 'Bibliothèque - ' + TITLE
	template_name = 'gallery/library.html'
	view_name = 'gallery:library'
	nav_selected = ('library',)
	action_elements = ('select', 'download', 'add', 'delete', 'share')
	action_search_view = view_name

	def get(self, request):
		question = request.GET.get('query', None)
		context = self.get_base_context()

		if question is not None:
			context['previousSearch'] = question
			albums = Album.objects.filter(user=request.user, name__unaccent__icontains=question).exclude(category='S', name='Search')
		else:
			albums = Album.objects.filter(user=request.user).exclude(category='S', name='search')
		
		context['albums'] = albums

		return render(request, self.template_name, context)

	def post(self, request):
		actions = {
			'download': self.download_albums,
			'add': self.add_albums,
			'delete': self.delete_albums,
			'share': self.share_albums
		}

		default_fct = lambda r: redirect(self.view_name)
		action = actions.get(request.POST.get('action', None), default_fct)
		return action(request)

	def loop_albums_from_request(self, request):
		for pk in request.POST.get('content', '').strip().split(','):
			if pk.isdigit():
				pk = int(float(pk))
				album = get_object_or_404(Album, pk=pk, user=request.user)
				yield album

	def download_albums(self, request):
		if not request.POST['content'].strip():
			return redirect(self.view_name)
			
		zippath = settings.TMP_ROOT / 'zipfiles' / (get_illegible_name() + '.zip')
		filepaths = set()

		with zipfile.ZipFile(zippath, 'w', compression=zipfile.ZIP_DEFLATED) as file:
			for album in self.loop_albums_from_request(request):
				parent_dir = album.get_category_display() + ' - ' + album.name

				for picture in album.pictures.all():
					filepath = os.path.join(parent_dir, picture.filename)
				
					if filepath in filepaths:
						name, ext = os.path.splitext(filepath)
						filepath = name + ' ({})' + ext
						index = 2

						while filepath.format(index) in filepaths:
							index += 1
						filepath = filepath.format(index)
					filepaths.add(filepath)
					file.write(picture.image.path, arcname=filepath)
		
		return FileResponse(open(zippath, 'rb'), as_attachment=True, filename='Photos.zip')

	def add_albums(self, request):
		album_name = request.POST.get('content', '').strip()

		if album_name:
			filters = {
				'user': request.user,
				'category': 'U',
				'name': album_name
			}

			if Album.objects.filter(**filters).exists():
				return redirect(self.view_name)
			album = get_or_create_album(**filters)
			return redirect(AlbumView.view_name, album_id=album.id)
		
		self.errors['other'] = 'Le nom d\'album ne peut pas être vide'
		return redirect(self.view_name)

	def delete_albums(self, request):
		for album in self.loop_albums_from_request(request):
			if album.category == 'U':
				album.delete()
		return redirect(self.view_name)

	def share_albums(self, request):
		for album in self.loop_albums_from_request(request):
			pass
			# TODO: find a way to share albums
		return redirect(self.view_name)


class AlbumView(LoginRequiredMixin, BaseView):
	title = 'Album - ' + TITLE
	template_name = 'gallery/album.html'
	view_name = 'gallery:album'
	nav_selected = ('album',)
	action_elements = ('select', 'upload', 'download', 'delete', 'share', 'hide')
	action_search_view = view_name

	def search_for_date(self, question, pictures):
		patterns = (
			{
				'regex': r'(\s|^)[0-9]{1,2} [a-zA-Z]+ [0-9]{4}(\s|$)',
				'precision': 'day',
				'letter_month': True
			},
			{
				'regex': r'(\s|^)[0-9]{1,2}[\s/][0-9]{1,2}[\s/][0-9]{4}(\s|$)',
				'precision': 'day',
				'letter_month': False
			},
			{
				'regex': r'(\s|^)[a-zA-Z]+ [0-9]{4}(\s|$)',
				'precision': 'month',
				'letter_month': True
			},
			{
				'regex': r'(\s|^)[0-9]{1,2}[\s/][0-9]{4}(\s|$)',
				'precision': 'month',
				'letter_month': False
			},
			{
				'regex': r'(\s|^)[0-9]{4}(\s|$)',
				'precision': 'year',
				'letter_month': False
			}
		)

		for pattern in patterns:
			match = re.search(pattern['regex'], question)

			if match:
				a, b = match.span()
				datestr = question[a:b].replace('/', ' ').strip()

				if pattern['precision'] == 'day':
					day, month, year = datestr.split()

					if pattern['letter_month']:
						month = translate_month(month)

					date = datetime.datetime.strptime(day + ' ' + month + ' ' + year, '%d %m %Y')
					pictures = pictures.filter(date__year=date.year, date__month=date.month, date__day=date.day)
				elif pattern['precision'] == 'month':
					month, year = datestr.split()

					if pattern['letter_month']:
						month = translate_month(month)

					date = datetime.datetime.strptime(month + ' ' + year, '%m %Y')
					pictures = pictures.filter(date__year=date.year, date__month=date.month)
				else:
					year = datestr

					date = datetime.datetime.strptime(year, '%Y')
					pictures = pictures.filter(date__year=date.year)

				question = question.replace(question[a:b], '')
				break

		return pictures, question

	def search_for_size(self, question, pictures):
		rsize = r'(\s|^)[0-9]+x[0-9]+(\s|$)'
		match = re.search(rsize, question)

		if match:
			a, b = match.span()
			width, height = question[a:b].split('x')
			question = question.replace(question[a:b], '')

			return pictures.filter(width=int(width), height=int(height)), question
		return pictures, question

	def search_for_tags(self, question, pictures):
		words = question.split()
		
		for word in words:
			if word:
				pictures = pictures.intersection(Picture.objects.filter(tags__unaccent__icontains=word))
		return pictures, question

	def get_pages(self, album):
		configs = []
		current_config = ''
		pictures = album.pictures.all()

		for picture in pictures:
			shape = get_picture_shape(picture)

			if shape == 's':
				if current_config not in ('', 's', 'ss', 'sss', 'sl', 'sh', 'l', 'h', 'ls', 'hs'):
					configs.append(current_config)
					current_config = ''
			elif shape == 'l':
				if current_config not in ('', 's', 'ss', 'l'):
					configs.append(current_config)
					current_config = ''
			elif shape == 'h':
				if current_config not in ('', 's', 'ss', 'h'):
					configs.append(current_config)
					current_config = ''
			current_config += shape

		if current_config:
			configs.append(current_config)

		if len(configs) % 2:
			configs.append('')

		picIndex = 0
		pages = [None] * len(configs)

		for index, config in enumerate(configs):
			if index % 2:
				pages[index] = ((pictures[picIndex:picIndex+len(config)], config))
			else:
				pages[len(configs) - index - 2] = ((pictures[picIndex:picIndex+len(config)], config))
			picIndex += len(config)
		return pages

	def get(self, request, album_id=None, page_id=0):
		question = request.GET.get('query', None)
		context = self.get_base_context()
		context['form'] = PictureForm()

src/gallery/templates/layouts/actionbar.html
{% load static %}
<div class="actionbar{% if cls %} {{ cls }}{% endif %}">
	<nav class="actionbar__nav">
		{% if 'back' in actionElements %}
			<button class="actionbar__element actionbar__button" onclick="window.history.back();" title="Retour">
				<img src="{% static 'gallery/img/previous.svg' %}">
			</button>
		{% endif %}
		{% if 'select' in actionElements %}
			<button class="actionbar__element actionbar__button" onclick="actionSelect();" title="Sélectionner">
				<img src="{% static 'gallery/img/select.svg' %}">
			</button>
		{% endif %}
		{% if 'upload' in actionElements %}
			<button class="actionbar__element actionbar__button" onclick="actionUpload('{{ form.image.id_for_label }}');" title="Envoyer">
				<img src="{% static 'gallery/img/upload.svg' %}">
			</button>
		{% endif %}
		{% if 'download' in actionElements %}
			<button class="actionbar__element actionbar__button{% if 'select' in actionElements %} actionbar__element--disabled actionbar__element--selectable{% endif %}" onclick="actionDownload();" title="Télécharger">
				<img src="{% static 'gallery/img/download.svg' %}">
			</button>
		{% endif %}
		{% if 'add' in actionElements %}
			<button class="actionbar__element actionbar__button" onclick="actionAdd();" title="Ajouter">
				<img src="{% static 'gallery/img/add.svg' %}">
			</button>
		{% endif %}
		{% if 'delete' in actionElements %}
			<button class="actionbar__element actionbar__button{% if 'select' in actionElements %} actionbar__element--disabled actionbar__element--selectable{% endif %}" onclick="actionDelete();" title="Supprimer">
				<img src="{% static 'gallery/img/delete.svg' %}">
			</button>
		{% endif %}
		<!--{% if 'share' in actionElements %}
			<button class="actionbar__element actionbar__button{% if 'select' in actionElements %} actionbar__element--disabled actionbar__element--selectable{% endif %}" onclick="actionShare();" title="Partager">
				<img src="{% static 'gallery/img/share.svg' %}">
			</button>
		{% endif %}-->
		{% if 'hide' in actionElements %}
			<button class="actionbar__element actionbar__button{% if 'select' in actionElements %} actionbar__element--disabled actionbar__element--selectable{% endif %}" onclick="actionHide();" title="Cacher">
				<img src="{% static 'gallery/img/hide.svg' %}">
			</button>
		{% endif %}
	</nav>
	<form class="actionbar__search" method="get" action="{% if viewName == 'gallery:library' %}{% url 'gallery:library' %}{% elif viewName == 'gallery:album' %}{% url 'gallery:album' album_id=album.id %}{% elif viewName == 'gallery:picture' %}{% url 'gallery:album' %}{% endif %}" id="search-form">
		{% csrf_token %}
		<label for="search-input" class="actionbar__element actionbar__label">
			<input type="search" name="query" id="search-input" value="{{ previousSearch }}" placeholder="{% if viewName == 'gallery:library' %}Entre un nom d'album{% else %}Entre une date ou une taille d'image{% endif %}">
			<img src="{% static 'gallery/img/search.svg' %}" title="Rechercher" onclick="document.getElementById('search-form').submit();">
		</label>
	</form>
	<!-- hidden forms -->
	<form style="display: none;" method="post" action="{% if viewName == 'gallery:album' %}{% url viewName album_id=album.id %}{% elif viewName == 'gallery:picture' %}{% url 'gallery:album' %}{% else %}{% url viewName %}{% endif %}" id="action-form">
		{% csrf_token %}
		<input type="hidden" name="action" value="" id="actiontype-input">
		<input type="hidden" name="content" value="" id="actioncontent-input">
	</form>
	<form style="display: none;" method="post" enctype="multipart/form-data" action="{% if viewName == 'gallery:album' %}{% url viewName album_id=album.id %}{% elif viewName == 'gallery:picture' %}{% url 'gallery:album' %}{% else %}{% url viewName %}{% endif %}" id="upload-form">
		{% csrf_token %}
		<input type="hidden" name="action" value="upload">
		{{ form.image }}
	</form>
</div>

src/gallery/templates/layouts/album.html
{% load gallery %}
<div class="album">
	{% if pages %}
		{% for page in pages %}
			{% if forloop.counter0|divisibleby:2 %}
				<div class="album__page album__page--right{% if page|index:1 %} album__page--{{ page|index:1 }}{% else %} album__page--empty{% endif %}{% if forloop.revcounter0 == 1 %} album__page--title{% endif %}" onclick="contentnavNext();">
			{% else %}
				<div class="album__page album__page--left{% if page|index:1 %} album__page--{{ page|index:1 }}{% else %} album__page--empty{% endif %}{% if forloop.revcounter == 1 %} album__page--last{% endif %}" onclick="contentnavPrevious();">
			{% endif %}
			<div class="album__content">
			{% for picture in page|index:0 %}
				<div class="album__picture" id="picture-{{ picture.id }}" onclick="actionActiveSelection(event, {{ picture.id }}, '{% url 'gallery:picture' picture_id=picture.id %}');">
					{% include 'components/cloud.html' with cls='album__selectbox' %}
					<img src="{{ picture.image.url }}">
				</div>
			{% endfor %}
				</div>
			</div>
		{% endfor %}
	{% else %}
		<div class="album__page album__page--right album__page--title album__page--empty" onclick="contentnavNext();">
			<div class="album__content">
				<p>{% if album.category == 'S' and album.name == 'search' %}Aucune photo trouvée{% elif album.category == 'S' and album.name == 'hidden' %}Aucune photo cachée{% else %}Cet album est vide<br> C'est le début d'une nouvelle histoire{% endif %}</p>
			</div>
		</div>
		<div class="album__page album__page--left album__page--last album__page--empty" onclick="contentnavPrevious();">
			<div class="album__content"></div>
		</div>
	{% endif %}
	<div class="album__bgline album__bgline--left"></div>
	<div class="album__bgline album__bgline--right"></div>
</div>

src/gallery/templates/layouts/contentnav.html
{% load static %}
<div class="contentnav">
	<div class="contentnav__element contentnav__element--previous" onclick="contentnavPrevious();">
		<img src="{% static 'gallery/img/previous.svg' %}" alt="<">
		<p>{{ textPrevious }}</p>
	</div>
	{% if text %}
	<p class="contentnav__text">{{ text }}</p>
	{% endif %}
	<div class="contentnav__element contentnav__element--next" onclick="contentnavNext();">
		<p>{{ textNext }}</p>
		<img src="{% static 'gallery/img/next.svg' %}" alt=">">
	</div>
</div>

src/gallery/templates/layouts/cover.html
<div class="cover{% if forloop.counter == 1 %} cover--current{% elif forloop.counter == 2 %} cover--next{% endif %}" onclick="actionActiveSelection(event, {{ album.id }}, '{% url 'gallery:album' album_id=album.id %}');" id="cover-{{ album.id }}">
	<div class="cover__bgline"></div>
	{% include 'components/cloud.html' with cls='cover__selectbox' %}
	{% if album.cover %}
		<img class="cover__image" src="{{ album.cover.image.url }}" alt="Photo de couverture">
	{% endif %}
	<p class="cover__title{% if not album.cover %} cover__title--alone{% endif %}">{{ album.name.capitalize }}</p>
</div>

src/gallery/templates/layouts/footer.html
<footer class="footer{% if cls %} {{ cls }}{% endif %}">
	<div class="footer__container">
		<p class="footer__element">© 2021 - {{ appName }} Team</p>
		<p class="footer__element">v{{ version }}</p>
		<a href="" class="footer__element">Contact</a>
	</div>
</footer>

src/gallery/templates/layouts/header.html
<header class="header{% if cls %} {{ cls }}{% endif %}">
	{% include 'components/icon.html' %}
	{% if navBar %}
		<nav class="header__nav">
			<a href="{% url 'gallery:album' %}" class="header__button{% if 'album' in navSelected %} header__button--selected{% endif %}">
				<p>Album</p>
			</a>
			<a href="{% url 'gallery:library' %}" class="header__button{% if 'library' in navSelected %} header__button--selected{% endif %}">
				<p>Bibliothèque</p>
			</a>
			<a href="{% url 'gallery:settings' %}" class="header__button{% if 'settings' in navSelected %} header__button--selected{% endif %}">
				<p>Compte</p>
			</a>
		</nav>
	{% endif %}
</header>

src/gallery/templates/layouts/notebook.html
<div class="notebook">
	<div class="notebook__sheet">
		<div class="notebook__line">
			<h2>Détails</h2>
		</div>
		<div class="notebook__line">
			<p></p>
		</div>
		<div class="notebook__line">
			<p>Nom: {{ picture.filename }}</p>
		</div>
		<div class="notebook__line">
			<p>Date: {{ picture.date }}</p>
		</div>
		<div class="notebook__line">
			<p>Taille: {{ picture.width }}x{{ picture.height }}</p>
		</div>
		<div class="notebook__line">
			<p>Auteur: {{ picture.user.username }}</p>
		</div>
		{% for i in '00000'|make_list %}
			<div class="notebook__line">
				<p></p>
			</div>
		{% endfor %}
	</div>
	<div class="notebook__clip"></div>
</div>

src/gallery/templates/layouts/sectiontitle.html
<div class="sectiontitle{% if cls %} {{ cls }}{% endif %}">
	<div class="sectiontitle__title">
		<div class="sectiontitle__line"></div>
		<h2 class="sectiontitle__text">{{ text }}</h2>
		<div class="sectiontitle__line"></div>
	</div>
	<p class="sectiontitle__subtitle">{{ subtext }}</p>
</div>